server {            #HTTP
    listen  80;
    listen  [::]:80;
    
    server_name  chserv.ddns.net;

    location / {
        root   /Volum/nginx/www;
        allow all;
    }

    #error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen  443 ssl http2;
    listen  [::]:443 ssl http2;

    server_name chserv.ddns.net;

    ssl_certificate /etc/letsencrypt/live/chserv.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chserv.ddns.net/privkey.pem;

    location / {
         root   /Volum/nginx/www;
         index  index.html index.htm;
    }

    #error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
