version: '3'

services:
   nginx:
      image: nginx:stable-alpine
      container_name: nginxThree
      ports:
         - "8080:80"
      volumes:
         - Volume:/volum:rw
         - ./things/nginx/www:/volum/nginx/www
         - ./things/nginx/conf.d:/etc/nginx/conf.d
   server:
      image: centos:latest
      container_name: centosThree
      volumes:
         - Volume:/volum:rw
         - ./things/centos/scr:/volum/nginx/www/scr
      command: [/volum/nginx/www/scr/script]

volumes:
   Volume:
