server {            #HTTP
    listen  80;
    
    server_name  chserv.ddns.net;

#    location / {
#        root /volum/nginx/www;
#        index  index.html index.htm;
#    }

    location / {
        return 301 https://$host$request_uri;
    }  
}

server {            #HTTPS
    listen 443 ssl;

    server_name chserv.ddns.net;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    ssl_certificate /etc/letsencrypt/live/chserv.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chserv.ddns.net/privkey.pem;

    location /.well-known/acme-challenge/ {
        root /var/www/;
    }

    location / {
        root /volum/ngimx/www;
        index index.html index.htm;
    }
}

