# services:  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/www/index.html:/Volum/nginx/www/index.html
      - ./things/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - etc-letsencrypt:/etc/letsencrypt
  
  server:
    image: centos:latest
    container_name: centos
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/script:/Volum/nginx/www/scr/script
    command: [/Volum/nginx/www/scr/script]
  
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    container_name: certbotThree
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/www/index.html:/Volum/nginx/www/index.html
    command: certonly --webroot --webroot-path=/Volum/nginx/www/ --email urmi.98.ru@gmail.com --agree-tos --no-eff-email -d chserv.ddns.net
    command: [cp -r /etc/letsencrypt /Volum/nginx/www/ssl/]