version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - volume:/volum:rw
      - ./things/nginx/www:/volum/nginx/www
      - ./things/nginx:/etc/nginx/conf.d
      - ./things/certbot:/etc/letsencrypt
  server:
    image: centos:latest
    container_name: centos
    volumes:
      - volume:/volum:rw
      - ./things/nginx/scripts:/volum/nginx/www/scripts
    command: [/volum/nginx/www/scripts/script]

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - volume:/volum:rw
      - ./things/nginx/www:/var/www/certbot
      - ./things/certbot:/etc/letsencrypt
    command: [/etc/letsencrypt/scriptcertbot]
volumes:
  volume:

